/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\FemaleModelJeans.glb -r public 
*/

import React, { forwardRef } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export const FemaleModelJeans = forwardRef(function FemaleModelJeans(
  props,
  ref
) {
  const { scene } = useGLTF("/FemaleModelJeans.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  return (
    <group {...props} dispose={null} ref={ref}>
      <group scale={1.204}>
        <group position={[-0.187, 0.902, -0.016]}>
          <primitive object={nodes.GLTF_created_0_rootJoint} />
          <skinnedMesh
            geometry={nodes.Object_10.geometry}
            material={materials["toufa.001"]}
            skeleton={nodes.Object_10.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_11.geometry}
            material={materials["kuzi.001"]}
            skeleton={nodes.Object_11.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_12.geometry}
            material={materials["xiezi_1.001"]}
            skeleton={nodes.Object_12.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_13.geometry}
            material={materials["xiezi_2.001"]}
            skeleton={nodes.Object_13.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_15.geometry}
            material={materials["yanjing.001"]}
            skeleton={nodes.Object_15.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_17.geometry}
            material={materials["yanjing.001"]}
            skeleton={nodes.Object_17.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_7.geometry}
            material={materials["maoyi_1.001"]}
            skeleton={nodes.Object_7.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_8.geometry}
            material={materials["maoyi_2.001"]}
            skeleton={nodes.Object_8.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_9.geometry}
            material={materials["pifu.001"]}
            skeleton={nodes.Object_9.skeleton}
          />
        </group>
      </group>
    </group>
  );
});

useGLTF.preload("/FemaleModelJeans.glb");
