/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\FemaleModelDress.glb -r public 
*/

import React, { forwardRef } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export const FemaleModelDress = forwardRef(function FemaleModelDress(
  props,
  ref
) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/FemaleModelDress.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={ref} {...props} dispose={null}>
      <group name="Scene">
        <group name="Node_90" />
        <group name="Node_90001" position={[0, 0, -1.156]} />
        <group
          name="Sketchfab_model001"
          rotation={[-Math.PI / 2, 0, 3.015]}
          scale={1.3}
        >
          <group
            name="be827bbb5f314cda8ae4ff1c37c783eafbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="1"
                  position={[-50.138, 289.611, -184.484]}
                  rotation={[-0.785, 0.009, 0.009]}
                  scale={100}
                >
                  <group name="Object_5" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_6" />
                  </group>
                </group>
                <group
                  name="1001"
                  position={[-4.614, 28.082, -85.908]}
                  rotation={[-1.978, 0.009, 0.009]}
                  scale={16.914}
                >
                  <group name="Object_16" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_17001" />
                  </group>
                </group>
                <group
                  name="2"
                  position={[-88.666, 198.527, 177.443]}
                  rotation={[0.833, -0.298, -2.829]}
                  scale={-100}
                >
                  <group name="Object_8001" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_9001" />
                  </group>
                </group>
                <group name="ADA" rotation={[0, -0.876, 0]} scale={101.05}>
                  <group name="Object_19">
                    <primitive object={nodes._rootJoint} />
                    <group
                      name="Object_101"
                      rotation={[0, -0.876, 0]}
                      scale={101.05}
                    />
                    <group
                      name="Object_107"
                      rotation={[0, -0.876, 0]}
                      scale={101.05}
                    />
                    <group
                      name="Object_108"
                      rotation={[0, -0.876, 0]}
                      scale={101.05}
                    />
                    <group
                      name="Object_109"
                      rotation={[0, -0.876, 0]}
                      scale={101.05}
                    />
                    <group
                      name="Object_111"
                      rotation={[0, -0.876, 0]}
                      scale={101.05}
                    />
                    <group
                      name="Object_113"
                      rotation={[0, -0.876, 0]}
                      scale={101.05}
                    />
                    <group
                      name="Object_114"
                      rotation={[0, -0.876, 0]}
                      scale={101.05}
                    />
                    <group
                      name="Object_115"
                      rotation={[0, -0.876, 0]}
                      scale={101.05}
                    />
                    <group
                      name="Object_117"
                      rotation={[0, -0.876, 0]}
                      scale={101.05}
                    />
                    <group
                      name="Object_119"
                      rotation={[0, -0.876, 0]}
                      scale={101.05}
                    />
                    <group
                      name="Object_121"
                      rotation={[0, -0.876, 0]}
                      scale={101.05}
                    />
                    <group
                      name="Object_123"
                      rotation={[0, -0.876, 0]}
                      scale={101.05}
                    />
                    <group
                      name="Object_125"
                      rotation={[0, -0.876, 0]}
                      scale={101.05}
                    />
                    <group
                      name="Object_127"
                      rotation={[0, -0.876, 0]}
                      scale={101.05}
                    />
                    <group
                      name="Object_129"
                      rotation={[0, -0.876, 0]}
                      scale={101.05}
                    />
                    <group
                      name="Object_131"
                      rotation={[0, -0.876, 0]}
                      scale={101.05}
                    />
                    <group
                      name="Object_132"
                      rotation={[0, -0.876, 0]}
                      scale={101.05}
                    />
                    <group
                      name="Object_133"
                      rotation={[0, -0.876, 0]}
                      scale={101.05}
                    />
                    <group
                      name="Object_134"
                      rotation={[0, -0.876, 0]}
                      scale={101.05}
                    />
                    <group
                      name="Object_99"
                      rotation={[0, -0.876, 0]}
                      scale={101.05}
                    />
                    <skinnedMesh
                      name="Object_100"
                      geometry={nodes.Object_100.geometry}
                      material={materials.mini_pink_dress}
                      skeleton={nodes.Object_100.skeleton}
                    />
                    <skinnedMesh
                      name="Object_102"
                      geometry={nodes.Object_102.geometry}
                      material={materials.Sandal_Heels}
                      skeleton={nodes.Object_102.skeleton}
                    />
                    <skinnedMesh
                      name="Object_103"
                      geometry={nodes.Object_103.geometry}
                      material={materials.Sandal_Heels}
                      skeleton={nodes.Object_103.skeleton}
                    />
                    <skinnedMesh
                      name="Object_104"
                      geometry={nodes.Object_104.geometry}
                      material={materials.Sandal_Heels}
                      skeleton={nodes.Object_104.skeleton}
                    />
                    <skinnedMesh
                      name="Object_105"
                      geometry={nodes.Object_105.geometry}
                      material={materials.Sandal_Heels}
                      skeleton={nodes.Object_105.skeleton}
                    />
                    <skinnedMesh
                      name="Object_106"
                      geometry={nodes.Object_106.geometry}
                      material={materials.Sandal_Heels}
                      skeleton={nodes.Object_106.skeleton}
                    />
                    <skinnedMesh
                      name="Object_110"
                      geometry={nodes.Object_110.geometry}
                      material={materials.material_0}
                      skeleton={nodes.Object_110.skeleton}
                    />
                    <skinnedMesh
                      name="Object_112"
                      geometry={nodes.Object_112.geometry}
                      material={materials.hair}
                      skeleton={nodes.Object_112.skeleton}
                    />
                    <skinnedMesh
                      name="Object_116"
                      geometry={nodes.Object_116.geometry}
                      material={materials.hair}
                      skeleton={nodes.Object_116.skeleton}
                    />
                    <skinnedMesh
                      name="Object_118"
                      geometry={nodes.Object_118.geometry}
                      material={materials["Face.001"]}
                      skeleton={nodes.Object_118.skeleton}
                    />
                    <skinnedMesh
                      name="Object_120"
                      geometry={nodes.Object_120.geometry}
                      material={materials.material_0}
                      skeleton={nodes.Object_120.skeleton}
                    />
                    <skinnedMesh
                      name="Object_122"
                      geometry={nodes.Object_122.geometry}
                      material={materials.pelinha}
                      skeleton={nodes.Object_122.skeleton}
                    />
                    <skinnedMesh
                      name="Object_124"
                      geometry={nodes.Object_124.geometry}
                      material={materials["Face.001"]}
                      skeleton={nodes.Object_124.skeleton}
                    />
                    <skinnedMesh
                      name="Object_126"
                      geometry={nodes.Object_126.geometry}
                      material={materials.Body}
                      skeleton={nodes.Object_126.skeleton}
                    />
                    <skinnedMesh
                      name="Object_128"
                      geometry={nodes.Object_128.geometry}
                      material={materials.hair}
                      skeleton={nodes.Object_128.skeleton}
                    />
                    <skinnedMesh
                      name="Object_130"
                      geometry={nodes.Object_130.geometry}
                      material={materials.hair}
                      skeleton={nodes.Object_130.skeleton}
                    />
                  </group>
                </group>
                <group
                  name="c"
                  position={[-170.007, 107.479, 208.467]}
                  rotation={[0, 0.901, -0.063]}
                  scale={100}
                >
                  <group name="Object_11001" />
                </group>
                <group
                  name="calcinha001"
                  rotation={[0, -0.876, 0]}
                  scale={101.05}
                />
                <group
                  name="glass"
                  position={[2.535, 86.405, -87.308]}
                  rotation={[0, -0.218, 0]}
                  scale={[41.842, 108.876, 161.931]}
                />
                <group
                  name="heels001"
                  rotation={[0, -0.876, 0]}
                  scale={101.05}
                />
                <group
                  name="LOD_1_Group_0_Sub_1__Hair00_mat001"
                  rotation={[0, -0.876, 0]}
                  scale={101.05}
                />
                <group
                  name="LOD_1_Group_0_Sub_1__pl2050_Face_Mat001"
                  rotation={[0, -0.876, 0]}
                  scale={101.05}
                />
                <group
                  name="LOD_1_Group_0_Sub_2__Hair01_mat001"
                  rotation={[0, -0.876, 0]}
                  scale={101.05}
                />
                <group
                  name="LOD_1_Group_0_Sub_2__pl2050_Hair_Mat001"
                  rotation={[0, -0.876, 0]}
                  scale={101.05}
                />
                <group
                  name="LOD_1_Group_0_Sub_3__Hair02_mat001"
                  rotation={[0, -0.876, 0]}
                  scale={101.05}
                />
                <group
                  name="LOD_1_Group_0_Sub_3__pl2000_Dress_Mat002"
                  rotation={[0, -0.876, 0]}
                  scale={101.05}
                />
                <group
                  name="LOD_1_Group_0_Sub_5__pl2050_Tearline_Mat001"
                  rotation={[0, -0.876, 0]}
                  scale={101.05}
                />
                <group
                  name="LOD_1_Group_0_Sub_6__pl2050_Eye_Mat001"
                  rotation={[0, -0.876, 0]}
                  scale={101.05}
                />
                <group
                  name="LOD_1_Group_0_Sub_7__pl2050_Eye_cover_Mat001"
                  rotation={[0, -0.876, 0]}
                  scale={101.05}
                />
                <group
                  name="LOD_1_Group_1_Sub_2__pl2000_Body_Mat002"
                  rotation={[0, -0.876, 0]}
                  scale={101.05}
                />
                <group
                  name="LOD_1_Group_200_Sub_1__pl2000_Gun_Mat002"
                  rotation={[0, -0.876, 0]}
                  scale={101.05}
                />
                <group
                  name="LOD_1_Group_20_Sub_1__sm73_431_LListTagGeneral01A_A_Mat_b11001"
                  rotation={[0, -0.876, 0]}
                  scale={101.05}
                />
                <group
                  name="LOD_1_Group_20_Sub_2__sm73_431_LListTagGeneral01A_A_Mat_8e4001"
                  rotation={[0, -0.876, 0]}
                  scale={101.05}
                />
                <group
                  name="LOD_1_Group_2_Sub_1__pl2000_Shoes_Mat002"
                  rotation={[0, -0.876, 0]}
                  scale={101.05}
                />
                <group
                  name="LOD_1_Group_2_Sub_1__pl2050_Flame_Mat001"
                  rotation={[0, -0.876, 0]}
                  scale={101.05}
                />
                <group
                  name="LOD_1_Group_2_Sub_2__pl2000_Body_Mat002"
                  rotation={[0, -0.876, 0]}
                  scale={101.05}
                />
                <group
                  name="LOD_1_Group_2_Sub_2__pl2050_Glass_Mat001"
                  rotation={[0, -0.876, 0]}
                  scale={101.05}
                />
                <group
                  name="mini_pink_dress"
                  rotation={[0, -0.876, 0]}
                  scale={101.05}
                />
                <group
                  name="Point"
                  position={[0, 290.761, 103.131]}
                  scale={100}
                >
                  <group name="Object_13001" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_14" />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
});

useGLTF.preload("/FemaleModelDress.glb");
