/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\MaleModel10.glb -r public 
*/

import React, { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";

export const MaleModelSuit = forwardRef(function MaleModelSuit(props, ref) {
  const { nodes, materials } = useGLTF("/MaleModelSuit.glb");
  return (
    <group {...props} dispose={null} ref={ref}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.023}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={
              nodes.rp_dennis_posed_004_100k_rp_dennis_posed_004_100k_mat_0
                .geometry
            }
            material={materials.rp_dennis_posed_004_100k_mat}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </group>
  );
});

useGLTF.preload("/MaleModelSuit.glb");
